name: vanplan
description: "The go-to platform for planning and documenting van electrical and water system upgrades"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management - Riverpod 3.0 (modern syntax)
  flutter_riverpod: ^3.0.0
  
  # Icon Generation
  flutter_launcher_icons: ^0.13.1
  
  # Firebase - Updated to latest stable versions
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1
  
  # Navigation - Updated to latest stable
  go_router: ^16.2.0
  
  # UI & Images - Updated versions
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.15
  
  # Graph View for System Topology
  graphview: ^1.2.0
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utilities
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Add your assets here
  assets:
    - assets/images/
    - assets/icons/
  
  # Add custom fonts here
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#FF6B35"
    theme_color: "#FF6B35"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
  
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  
  # Optional: Create adaptive icons for Android
  adaptive_icon_background: "#FF6B35"
  adaptive_icon_foreground: "assets/icons/icon.png"