// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6VTkZgyGo-6NQmbliiAgTRSw-s6Q1kQs',
    appId: '1:144621361122:web:976c06a9f29b9241848bbb',
    messagingSenderId: '144621361122',
    projectId: 'vanplan-441af',
    authDomain: 'vanplan-441af.firebaseapp.com',
    storageBucket: 'vanplan-441af.firebasestorage.app',
    measurementId: 'G-L4MQJC7CG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRwH5RYGTDOFUY4E0fY3k54tRreSoG_c',
    appId: '1:144621361122:android:37ce6984de2fd801848bbb',
    messagingSenderId: '144621361122',
    projectId: 'vanplan-441af',
    storageBucket: 'vanplan-441af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmK01r-fs6ohaivExMcg3cGIxP6L-pejM',
    appId: '1:144621361122:ios:54cd158a95d11ba3848bbb',
    messagingSenderId: '144621361122',
    projectId: 'vanplan-441af',
    storageBucket: 'vanplan-441af.firebasestorage.app',
    iosBundleId: 'com.vanplan.app.vanplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmK01r-fs6ohaivExMcg3cGIxP6L-pejM',
    appId: '1:144621361122:ios:54cd158a95d11ba3848bbb',
    messagingSenderId: '144621361122',
    projectId: 'vanplan-441af',
    storageBucket: 'vanplan-441af.firebasestorage.app',
    iosBundleId: 'com.vanplan.app.vanplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6VTkZgyGo-6NQmbliiAgTRSw-s6Q1kQs',
    appId: '1:144621361122:web:1ac59da39b3fcc8b848bbb',
    messagingSenderId: '144621361122',
    projectId: 'vanplan-441af',
    authDomain: 'vanplan-441af.firebaseapp.com',
    storageBucket: 'vanplan-441af.firebasestorage.app',
    measurementId: 'G-G1LWDLQF4W',
  );
}
